fix latin_basic.h compilation error
error: invalid new-expression of abstract class type 'LatinBasicCharset'
 because the following virtual functions are pure within 'LatinBasicCharset':
     virtual word Char(word index) = 0;
                  ^~~~